### ISSUE TITLE
Error "Unknown substitution in Program"

### ISSUE THREAD

**Issue by rasenplanscher** [estools/estemplate#5]
I'm using this through [gulp-wrap-js](https://github.com/RReverser/gulp-wrap-js) and I have one step wrapping my files in IIFEs. Today, I added another one before that, adding some boilerplate code to a specific file, like so:
```
gulp.src('**/*.js')
.pipe(gulpIf(
    'special.js',
    wrapJs([
        'var boilerplate = {};',
        '%= body %'
    ].join('\n'))
))
.pipe(wrapJs([
    '(function () {',
    '"use strict";',
    '%= body %',
    '})();'
].join('\n')))
.pipe(gulp.dest('build/'))
```

That caused the error message "Unknown substitution in Program". I tracked that down and found that merely adding `'Program': 'body'` to `spread` in `estemplate.js` fixes that with no apparent downside. Is there a specific reason that this use-case hasn't been covered, am I missing something?

**Comment by RReverser** [comment]
No really specific use case - feel free to PR.

**Comment by rasenplanscher** [comment]
Will you publish to npm, or am I supposed to do that?

**Comment by RReverser** [comment]
If you wanted this to be published asap, you could just ask. Being polite doesn't harm ;)

**Comment by rasenplanscher** [comment]
I didn't mean to be brash, my question was actually meant as an inquiry into your intentions – I can see how my question might be mistaken as an obtrusive request, though. I'm sorry for that :)

Sooo, would you be so kind as to publish this soon? Then I could remove the workaround I have currently in place.

**Comment by RReverser** [comment]
Sure, will try to do later today.
